### ISSUE TITLE
Joey's Feedback

### ISSUE THREAD

**Issue by simon-mo** [ucbrise/clipper-tutorials#11]
Here are some Joey's feedback:

## 0-Welcome Notebook

It is possible (maybe...) that people will have never seen jupyter lab before or used a notebook. You might want to have a super fast crash course in notebooks as a pre-notebook. 

- this is a notebook (code + markdown) (edited)
- this is jupyter lab an interactive environment for running python
- and this is how you run a cell
- briefly review what docker is and list a few commands (in case ppl are not listening)

## 1- Part01-Clipper-Basics

- [ ] (Rehan) After starting clipper you might want to have them inspect the docker cluster using docker command with the ! bash command in the notebook; otherwise its hard to get an appreciation for what just happened after launching the cluster
- [ ] (Rehan) Move the h = .02 constant to the visualization cell
- [ ] (Rehan) you might also want to provide a note about how long a particular cell should take to complete: esp. the python closure deployer

**Comment by jegonzal** [comment]
Can we add doc strings to all the functions we define in the tutorial?  In particular later pytorch predict functions could use doc strings describing inputs and returned values.

**Comment by jegonzal** [comment]
Not critical but I think you can avoid creating temporary files in ```# Create a temp file to write to
        tmp = tempfile.NamedTemporaryFile('wb', delete=False, suffix='.jpg')
        tmp.write(io.BytesIO(img).getvalue())
        tmp.close()
        
        # Pre-process image
        img_tensor = preprocess(PIL.Image.open(tmp.name, 'r'))
        img_tensor.unsqueeze_(0)
        img_tensors.append(img_tensor)```

**Comment by jegonzal** [comment]
Also don't use `n` as a variable name.  Call it `neural_network` or something ...

**Comment by jegonzal** [comment]
Does the pong tutorial shut down the first tutorial cluster?  It appears to do that which is fine but you might want to make a note.

**Comment by jegonzal** [comment]
In the pong tutorial, I forgot to update the function and created the endpoint with the wrong function. I could not go back and update the endpoint (even changing the version).  I think this is before we separated creating applications and linking models. Can we use the same "core functions" in the pong tutorial as in the first tutorial?  First create the pong application and then link the model.

**Comment by simon-mo** [comment]
Everything is fixed. Thanks @jegonzal for the extensive feedback.
